[build]
  command = "npm run build:prod"
  publish = ".next"
  functions = ".next/server/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
